[package]
name = "crazyradio"
version = "0.1.5"
authors = ["Arnaud Taffanel <arnaud@taffanel.org>"]
edition = "2018"
description = "Crazyradio USB dongle driver"
readme = "README.md"
repository = "https://github.com/ataffanel/crazyradio-rs"
license = "MIT"
keywords = ["nrf24", "crazyflie"]
categories = ["hardware-support"]
exclude = [
    ".github/*"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.5"
serde = { version = "1.0", features = ["derive"], optional = true }
thiserror = "1.0"

[dev-dependencies]
serde_json = "1.0"

[features]
serde_support = ["serde"]
