[package]
name = "crazyradio"
version = "0.1.0"
authors = ["Arnaud Taffanel <arnaud@taffanel.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rusb = "0.5"
